# Generated by Django 4.2.3 on 2023-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterField(
            model_name='patient',
            name='pet_name',
            field=models.CharField(max_length=30),
        ),
    ]
